# frozen_string_literal: true

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = "test/**/*_test.rb"
end

RSpec::Core::RakeTask.new(:unit) do |t|
  t.pattern = "test/unit/**/*_test.rb"
end

RSpec::Core::RakeTask.new(:integration) do |t|
  t.pattern = "test/integration/**/*_test.rb"
end

task default: :unit
