name: Release Go pgx Connector

permissions: {}

on:
  push:
    tags:
      - "go/pgx/v*"

jobs:
  wait-for-ci:
    name: Wait for CI to pass
    runs-on: ubuntu-latest
    steps:
      - uses: lewagon/wait-on-check-action@78dd4dd5d9b337c14c3c81f79e53bf7d222435c1 # v1.6.1
        with:
          ref: ${{ github.sha }}
          running-workflow-name: "Wait for CI to pass"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          check-regexp: "build"

  update-changelog:
    needs: wait-for-ci
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/update-changelog.yml
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit
