name: Publish Postgres.js

permissions: {}

on:
  push:
    tags:
      - "node/postgres-js/v*"

defaults:
  run:
    working-directory: node/postgres-js

jobs:
  wait-for-ci:
    name: Wait for CI to pass
    runs-on: ubuntu-latest
    steps:
      - uses: lewagon/wait-on-check-action@78dd4dd5d9b337c14c3c81f79e53bf7d222435c1 # v1.6.1
        with:
          ref: ${{ github.sha }}
          running-workflow-name: "Wait for CI to pass"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          check-regexp: "Postgres\\.js tests"

  publish:
    needs: wait-for-ci
    runs-on: ubuntu-latest
    environment: NPM
    permissions:
      id-token: write # required for trusted publishing
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "25"
          registry-url: "https://registry.npmjs.org"

      - name: Set version from tag
        run: |
          VERSION=${GITHUB_REF_NAME#node/postgres-js/v}
          echo "Setting version to $VERSION"
          npm version "$VERSION" --no-git-tag-version --allow-same-version

      - run: |
          npm ci
          npm run build:prod

      - run: npm publish --provenance

  update-changelog:
    needs: publish
    uses: ./.github/workflows/update-changelog.yml
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit
