name: Publish Python Connector to PyPI

permissions: {}

on:
  push:
    tags:
      - "python/connector/v*"

defaults:
  run:
    working-directory: python/connector

jobs:
  wait-for-ci:
    name: Wait for CI to pass
    runs-on: ubuntu-latest
    steps:
      - uses: lewagon/wait-on-check-action@78dd4dd5d9b337c14c3c81f79e53bf7d222435c1 # v1.6.1
        with:
          ref: ${{ github.sha }}
          running-workflow-name: "Wait for CI to pass"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          check-regexp: "Python connector"

  build:
    name: Build python distribution packages
    needs: wait-for-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7

      - name: Build distribution packages
        run: uv build

      - name: Store the distribution packages
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: python-package-distributions
          path: python/connector/dist/

  publish-to-pypi:
    name: Publish Python distribution packages to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/aurora-dsql-python-connector
    permissions:
      id-token: write # required by pypa/gh-action-pypi-publish

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution package to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1

  update-changelog:
    needs: publish-to-pypi
    uses: ./.github/workflows/update-changelog.yml
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit
